os: windows
language: node_js
node_js:
  - 16.5.0
env:
  - YARN_GPG=no
cache: yarn
script: yarn dist
deploy:
  skip_cleanup: true
  provider: script
  script: bash scripts/deploy.sh
  on:
    branch: master
